apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zgu48r754-nodejs 
  janus-idp.io/tekton: zgu48r754-nodejs
  backstage.io/kubernetes-id: zgu48r754-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zgu48r754-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml